Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,3 +43,11 @@ jobs:
           mvn --version
           gradle --version
           ant -version
+        env:
+          RESULT_VAR: $?
+          run: |
+            if ${RESULT_var} == 0; then
+            echo "Unit Testing has been Successfull"
+            else
+            echo " Fails"
+            fi
